name: Compile source.
on:
  push:
    branches:
      - master
      - main

jobs:
  Master:
    runs-on: ubuntu-latest

    container: alpine

    steps:
        - name: ^ Checkout
          uses: actions/checkout@v3

        - name: Set up environment.
          run: |
              apk add --no-cache jq curl
              echo "GIT_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
              echo "GIT_PROJECT_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
              echo "GIT_USERNAME=${{ github.repository_owner }}" >> $GITHUB_ENV
              echo "GIT_REPO=${{ github.repository }}" >> $GITHUB_ENV

        - name: testing
          run: |
            apk add --no-cache git bash
            export GIT_PROJECT_NAME="GamePlayer-8.github.io"
            git ls-remote --exit-code --heads https://$GIT_USERNAME:${{ secrets.GITHUB_TOKEN }}@github.com/$GIT_USERNAME/"$GIT_PROJECT_NAME" gh-pages
            echo $?
